version: '3.9'
services:
  junkiapp_api:
    container_name: rest_server
    build:
      context: .
      dockerfile: dockerfiles/service.dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./env/service.env
    depends_on:
      - mysql
    volumes:
      - ./:/junkia-service

  mysql:
    build:
      context: .
      dockerfile: dockerfiles/mysql.dockerfile
    env_file:
      - ./env/mysql.env
